[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
