[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
